name = "ArrayRadiation"
uuid = "bd679b92-6dae-455f-83b3-ba41583ebc1e"
authors = ["Erik Buer <buer94@gmail.com>"]
version = "0.1.2"

[deps]
LinearAlgebra = "37e2e46d-f89d-539d-b4ee-838fcccc9c8e"

[compat]
LinearAlgebra = "^1.6"
julia = "^1.6"

[extras]
Documenter = "e30172f5-a6a5-5a46-863b-614d45cd2de4"
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test", "Documenter"]
